:bug: Fix `echoerr`
vim-denops/deno-denops-std pull request #176
Opened 2023-04-05 07:14 UTC by Milly

Since `echo` runs asynchronously, we need to runs `echohl` as well.

2023-04-05 23:36 UTC, Shougo commented on denops_std/helper/echo.ts
> +    if !empty(a:highlight) | execute 'echohl' a:highlight | endif
```suggestion
    if a:highlight !=# '' | execute 'echohl' a:highlight | endif
```

2023-04-05 23:36 UTC, Shougo commented on denops_std/helper/echo.ts
> +    if !empty(a:highlight) | echohl None | endif
```suggestion
    if a:highlight !=# '' | echohl None | endif
```

2023-04-06 03:05 UTC, lambdalisue requested changes

2023-04-06 03:05 UTC, lambdalisue commented on denops_std/helper/echo.ts
>      });
Now we don't need `batch`.

2023-04-06 04:55 UTC, Milly commented
Changed suggestions and squashed all.

2023-04-06 08:57 UTC, lambdalisue approved these changes

2023-04-06 08:57 UTC, merged