:+1: Refine argument types for `buffer-function`
vim-denops/deno-denops-std pull request #196
Opened 2023-05-10 11:46 UTC by Milly

Added following types for arguments of buffer-function.

```typescript
export type BufExistsArg = string | number;
export type BufNameArg = string | number;
export type BufLnumArg = "$" | number;
```

It makes the meaning of the argument types easier to understand.

2023-05-10 12:05 UTC, 4513ECHO requested changes

2023-05-10 12:05 UTC, 4513ECHO commented on denops_std/function/buffer.ts
> +export type BufLnumArg = "$" | number;
We can use `"."` to refer cursor position.

```suggestion
export type BufLnumArg = "$" | "." | number;
```

2023-05-10 22:58 UTC, Shougo approved these changes

2023-05-11 00:37 UTC, lambdalisue approved these changes
LGTM

2023-05-11 00:37 UTC, merged