👍 Add Type Definitions for `cursor-functions`
vim-denops/deno-denops-std pull request #62
Opened 2021-07-17 17:25 UTC by kuuote

全然作業が進んでなくて申し訳ないですが、テストを書いてみたので一度Draft pull requestをしておこうと思います。

- テストの書き方に全く自信がないです
  - 現状入出力の型に対するテストしか書いていませんが、それでいいのか
  - ensureで動的にテストをしているが、TypeScript的に型が付いているのかに対するテストも書いた方がいいのか
  - というのが気になっています
- `types.ts`に色々生やしているが、この方針でいいのか見て頂きたいです

コミットメッセージや粒度が適当ですが、完成したらrebaseし直す予定です。

2021-07-17 17:34 UTC, lambdalisue requested changes
> 現状入出力の型に対するテストしか書いていませんが、それでいいのか

関数自体のテストは不要なので「対象の関数を正しく呼び出せているか？」さえ担保できればいいと思います。その方法が型チェックでも値チェックでも、楽なもので良いと思います。

> ensureで動的にテストをしているが、TypeScript的に型が付いているのかに対するテストも書いた方がいいのか

意図を理解できているか自身がないですが TypeScript 的な型がついているか？に関しては `ensure` を使っている限り `unknownutil` の領分だと思います（なので不要

2021-07-17 17:34 UTC, lambdalisue commented on denops_std/function/_manual.ts
> +export * from "./cursor.ts";
**must**

We must expose `types.ts` as well.

2021-07-17 17:34 UTC, lambdalisue commented on denops_std/function/types.ts
> +const mockScreenPos: ScreenPos = {
may

It's more like "A reference structure of ScreenPos" thus I prefer "refScreenPos" or a similar name

2021-07-18 10:30 UTC, kuuote commented
コメント書き直すの微妙なので一旦閉じてPRし直そうと思います

2021-07-18 10:30 UTC, closed without merging